#+TITLE: Machine Learning For X Market Forcasting

* Kaggle competition
** G-Research Crypto Competition
goal is maximize predicted price and actual price correlation.
*** data
We can see the different features included in the dataset. Specifically, the features included per asset are the following:

**** timestamp: All timestamps are returned as second Unix timestamps (the number of seconds elapsed since 1970-01-01 00:00:00.000 UTC). Timestamps in this dataset are multiple of 60, indicating minute-by-minute data.
**** Asset_ID: The asset ID corresponding to one of the crytocurrencies (e.g. Asset_ID = 1 for Bitcoin). The mapping from Asset_ID to crypto asset is contained in asset_details.csv.
**** Count: Total number of trades in the time interval (last minute).
**** Open: Opening price of the time interval (in USD).
**** High: Highest price reached during time interval (in USD).
**** Low: Lowest price reached during time interval (in USD).
**** Close: Closing price of the time interval (in USD).
**** Volume: Quantity of asset bought or sold, displayed in base currency USD.
**** VWAP: The average price of the asset over the time interval, weighted by volume. VWAP is an aggregated form of trade data.
:PROPERTIES:
:ID:       7052404e-236a-4794-812a-963c2294fb16
:END:
**** Target: Residual log-returns for the asset over a 15 minute horizon.
