#+TITLE: Rust Notes

* String
** String literal
string literal must be presented in the code.
string literal are immutable.
** String type
string type manages data allocated on the heap.j


* [[https://doc.rust-lang.org/reference/attributes.html][attributes]]
From what I understand attributes are as the name suggested, it attaches to an item.

** inner vs outer attributes
Therer are inner attributes (denotes with =#=)and outer attributes (denotes with =#!=).
** active vs inert attributes
An attribute is either active or inert. During attribute processing, active attributes remove themselves from the thing they are on while inert attributes stay on.

Note: Macros attribute are active. All other attributes are inert.
** class of attributes
Attributes can be classified into the following kinds:
- Built-in attributes
- Macro attributes
- Derive macro helper attributes
- Tool attributes




* [[https://doc.rust-lang.org/rust-by-example/mod.html][modules]]
* macros vs functionality
macros is a =metaprogramming= features in rust where mataprogramming refers to a snippet of code that produce other code.

macros are expanded =before the compiler interprets the meaning of the code=, so a macro can, for example, implement a trait on a given type. A function can’t, because it =gets called at runtime= and a trait needs to be implemented at compile time.

** [[https://doc.rust-lang.org/stable/book/ch19-06-macros.html][macros]]
macros must be called into scope while functions can be defined and called anywhere

The term macro refers to a family of features in Rust: declarative macros with macro_rules! and three kinds of procedural macros:

- Custom #[derive] macros that specify code added with the derive attribute used on structs and enums
- Attribute-like macros that define custom attributes usable on any item
- Function-like macros that look like function calls but operate on the tokens specified as their argument

* References (Borrowing) vs Shadowing (using =let=) vs Mutable v Ownership  vs Constant
=Constants= are never outof scope and always immutable.

=Variables= are created using =let= and are immutable by default.
when two variables are assigned the same name, value of the most recently assigned variables replaced the previously assigned (This includes obtianing new types as well.). This process is called =Shadowing=, just another name for creating new variable just with the same name. =Shadowing= allows name of variables to be reuseable.

Keep in mind that constraint of variables depends on the following:
- scope
- ownership (which variables have the ownership?)
- mutable vs immutable
- References (are you referencing mutable or immutable variable? )

** References (Borrowing)
=References= is specified by =&= and referenced variables are immutable by default.
To make referenced variables mutable, one must specify  =&mut var= when passing vars to function and specify arguments of function (=To make it clear that function will mutate the value=), as followed.
#+BEGIN_SRC rust
fn main() {
    let mut s = String::from("hello");

    change(&mut s);
}

fn change(some_string: &mut String) {
    some_string.push_str(", world");
}
#+END_SRC

#+RESULTS:
=References= has a major restriction that =only one mutable to a piece of data are allowed at a time (can't referenced two mutables at a time.)=. This restriction prevents =data race condition at runtime=.

#+BEGIN_SRC rust
fn main() {
    let mut s = String::from("hello");

    let r1 = &mut s;
    let r2 = &mut s;

    println!("{}, {}", r1, r2);
}
#+END_SRC

#+RESULTS:
: error: Could not compile `cargoAslqWM`.

In addition, =we also can't have a mutable reference while we have immutable one=.
#+BEGIN_SRC rust
fn main() {
    let mut s = String::from("hello");

    let r1 = &s; // no problem
    let r2 = &s; // no problem
    let r3 = &mut s; // BIG PROBLEM

    println!("{}, {}, and {}", r1, r2, r3);
}

#+END_SRC

#+RESULTS:
: error: Could not compile `cargo2QhYwB`.

** Ownership
memory in Rust is managed through ownership with a set of rules that the compiler check at compile time.

Ownership helps to clean up data stored in heap without using garbage collectors (=only 1 owner can own data. Other can borrow it, but they have to be polite by asking owner if they want to modify the data.=).

*** Ownership Rules
- each value in Rust has a variable that's called its owner.
- There can only be one owner at a time.
- When the owner goes out of scope, the value will be dropped.
