#+TITLE: Non Fungible Token Nft Note

* Blog :blog:
** TODO Framework to think about non-fungible token (NFT)?
:PROPERTIES:
:ID:       14cb59de-45e8-4aa3-8812-3701040fdd67
:END:
NFT and crypto currency can be thought of as two different types of token. Token can be thought of as store of value -- asset. NFT is a hetergeneous token while crypto current is a homogeneous token.

** TODO Survey on Technology of NFT
:PROPERTIES:
:ID:       b0b319ba-fa30-4d65-8eae-37341d75bb5b
:END:
ERC-721 and ERC-1155
** TODO Survey on Intelligent NFT (iNFT) [fn:1]
:PROPERTIES:
:ID:       5ca4c078-69b1-405d-8c69-222d0fcc632a
:END:
As of Feb 20 2022, accroding to [fn:1], Altered STate Machine (ASM), an iNFT company, is currently under patent pending where owners will have full rights to the machine-learning model for their iNFT.

There are three types of iNFT
1. AI-Generated NFTs
   NFT that is generated by AI.
2. NFT Embedded AI
   NFT that has AI capability.
3. AI-first NFT Infrastructure
  Implementation of full lifecycle iNFT infrastructure such as iNFT market place.

*** token mechanism
:PROPERTIES:
:ID:       d398fcea-eddf-4fe2-86dc-afb3360a92ab
:END:
Given that a user has his/her ML models. One user can have many models. Models are evaluated based on evaluation metrics. There are a set of data that are provided to solve a task. For any additional data, user use to train on the models that increase evaluation score. the data can be traded. For this mechanism to realize, there must exists a protocol that allow ML model to train on data without expose content of the data, and there must also exist a way to validate usefulness of data to your model. Other useful mechanism include creating & sell new indicators, create & sell ML models and create & train model optimization plan and create & train model training scheme.

Given an evaluation metrics,
* Footnotes

[fn:1] [[https://towardsai.net/p/artificial-intelligence/nfts-ai][NFTs & AI]]
