#+TITLE: Org Download Note

* Error
** Using powershell to save images. (I guess this function can replaced default function used in org download.)
*** actions logs
**** starting code doesn't work because powershell command doesn't creat file.
code is from [[https://github.com/abo-abo/org-download/issues/178#issuecomment-974772904][here]].
#+BEGIN_SRC emacs-lisp
(defun my-yank-image-from-win-clipboard-through-powershell()
  "to simplify the logic, use c:/Users/Public as temporary directoy, and move it into current directoy"
  (interactive)
  (let* ((powershell "/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe")
         ;; (file-name (format-time-string "screenshot_%Y%m%d_%H%M%S.png"))
         (file-name (format-time-string "tmp.txt"))
         ;; (file-path-powershell (concat "c:/Users/\$env:USERNAME/" file-name))
         (file-path-wsl (concat "./images/" file-name))
         )
    ;; (shell-command (concat powershell " -command \"(Get-Clipboard -Format Image).Save(\\\"C:/Users/\\$env:USERNAME/" file-name "\\\")\""))
    (shell-command (concat powershell " -command \"(Get-Clipboard -Format Image).Save(\\\"C:/Users/Public/" file-name "\\\")\""))
    (rename-file (concat "/mnt/c/Users/Public/" file-name) file-path-wsl)
    (insert (concat "[[file:" file-path-wsl "]]"))
    (message "insert DONE.")
    ))
#+END_SRC
I found that powershell command doesn't create .png file and it also doesn't produce any error.

I need to figure out how to save image from clipboard using powershell. (or wsl) This may be the only function that will make drag and drop behavior of org download works.

For further reading
- [[https://alexrampp.de/2020/11/07/how-to-paste-images-into-emacs-org-mode-running-in-windows-subsystem-for-linux/][HOW TO PASTE IMAGES INTO EMACS ORG-MODE RUNNING IN WINDOWS SUBSYSTEM FOR LINUX]]
- read the following [[https://github.com/microsoft/WSL/issues/4440][WSL2 clipboard not shared between Linux and Windows #4440]]
- [[https://discourse.joplinapp.org/t/uploading-clipboard-copied-image-automatically-to-cloud/19826][save imaged in clipboard to cloud]]
- [[https://askubuntu.com/questions/759651/how-to-copy-an-image-to-the-clipboard-from-a-file-using-command-line][how to copy an image to the clipboard from a file using command line?]]
- [[https://www.reddit.com/r/bashonubuntuonwindows/comments/be2q3l/how_do_i_copy_whole_text_from_vim_to_clipboard_at/el2vx7u/?utm_source=share&utm_medium=web2x][hwo do I copy whoel text from vim to clipbaord at once?]] ([[https://github.com/microsoft/WSL/issues/4440#issuecomment-638884035][here too]])
- [[https://www.reddit.com/r/emacs/comments/jepjlf/pasting_images_into_org_mode_on_wsl/][pasting images into org mode on WSL]]
