#+TITLE: Economic Note
#+filetags: economic
#+hugo_base_dir: /home/awannaphasch2016/org/projects/sideprojects/website/my-website/hugo/quickstart

* Blog :blog:
** Evolution of Asset Transaction
:PROPERTIES:
:EXPORT_FILE_NAME: Evolution of Asset Transaction
:ID:       d97b1200-f8af-4277-9786-fe3ce103bfa6
:END:

This essay is my interpretation of a discussion on "NFTing the World for the General Good" episode on Real Vision TV. The information in the essay are adapted to fit rational narrative that I have in my brain.

This is the beginning of the essay.

The four phases are categorized into the following
1. transaction an physical assets
2. transaction of electron
3. transaction of information
4. transaction of digital assets

Each phase increase efficiency of transactions which depends on three factors: object, process, and rules.

Focusing on economic perspective, one can think of an objects as entities with ownership and process as a automatic process of manipulating of objects. Example of processes are movement, composability, and duplication etc. Lastly, rules are constraints imposed upon computation of processes and objects.

Using analogy of physic, rules are physic law such as gravity. Gravity put constraint on movement (process) of objects.

Rules are given. No one can change the rules. However, given a set of rules, object and process can be manipulated.

This is a new idea that I have as of [2022-04-15 Fri], so notation may be imprecise, but I will try my best to explain.

$object = process_1(objects, process_2(...))$

I derived an equation of object as followed

where An object is a output of process. A process can take N number of process and M number of objects as parameters.

Each step of assets transaction evolution create new types of object and new type of process. Total value of wealth are expanded from creation and utilization of new objects and new processes. During the first phase, assets are physical assets such as tree and rock. Discovers and inventions of fire, weapon, road, car allows new creation of processes like toasting a bread, chopping tree, and riding a car. In the second phase, "transaction of electron" create new objects like electric, light bulb, and xray and new processes involving the objects. With the invention of computer, the next phase "transaction of information" begins. It allows movement of bits and bytes which represent information. This further increases efficiency of communication and exchange of information. However, information alone is not enough to compose and exchange digital assets. The missing puzzle is ownership. And the technology that allows for the digital assets to be exchanged is blockchain technology. New form of objects includes NFT and crypto. One may argue that digital assets already exists during "transaction of information" phase. That's correct. To be clear, blockchain technology doesn't create digital assets. Blockchain technology expands creation of new digital asset and enable digital assets to be transacted. Hence, the name of the blog.

This blog provide one mental framework to think about the world and emphasize on significant of blockchain technology.

That's it.
Peace.
** TODO Asset vs Property vs Security
:PROPERTIES:
:ID:       b3436ffd-1c76-486c-9a31-7b33d3018313
:END:

Property is things that can be owned. By definition, property exclude governance aspect. Properties of a property is open, permissionless, and unsensorable.

Property are better stored fo value than money because it has utility, but they are not a good medium of exchange.

Asset is things that hold value. In this case, value is evaluated based on suppply-demand mechanism.

Security is a financial instrument. It is a type of financial asset. Government of a country determines asset that can be categorized as security or non-security.
* Data
:PROPERTIES:
:ID:       84ff272e-0938-49be-bf52-e1020c0d00cd
:END:
#+BEGIN_SRC python :results output :cache yes
import requests
import json
import prettytable
from pathlib import Path
import pandas as pd
import numpy as np
headers = {'Content-type': 'application/json'}
data = json.dumps({"seriesid": ['LNS11300000'],"startyear":"2019", "endyear":"2022"})
p = requests.post('https://api.bls.gov/publicAPI/v1/timeseries/data/', data=data, headers=headers)
json_data = json.loads(p.text)
data_dir = Path("/home/awannaphasch2016/Data/Economics/us_bureau_of_labor_statistics/")
data = []
for series in json_data['Results']['series']:

    # x =prettytable.PrettyTable(["series id","year","period","value","footnotes"])
    seriesId = series['seriesID']
    for item in series['data']:
        year = item['year']
        period = item['period']
        value = item['value']
        footnotes=""
        # for footnote in item['footnotes']:
        #     if footnote:
        #         footnotes = footnotes + footnote['text'] + ','
        if 'M01' <= period <= 'M12':
            # x.add_row([seriesId,year,period,value,footnotes[0:-1]])
            data.append([seriesId,year,period,value))
    data_df = pd.DataFrame(data, columns=["series id","year","period","value"])
    data_df.to_csv(str(data_dir / (seriesId + '.txt')),'w')
    print(data_df.head)
    # output = open(str(data_dir / (seriesId + '.txt')),'w')
    # output.write (x.get_string())
    # output.write (x.get_string())
    # output.close()
print('done')
#+END_SRC

#+RESULTS[5fec3a60b3aa028cc17b92faf5f352ddaa7e01e3]:
: done
