#+TITLE: Economic Note
#+filetags: economic
#+hugo_base_dir: /home/awannaphasch2016/org/projects/sideprojects/website/my-website/hugo/quickstart

* Blog :blog:
** Evolution of Asset Transaction :asset:
:PROPERTIES:
:EXPORT_FILE_NAME: Evolution of Asset Transaction
:ID:       d97b1200-f8af-4277-9786-fe3ce103bfa6
:END:

Hello, guys

This essay is my interpretation of a discussion on "NFTing the World for the General Good" episode on Real Vision TV. The information in the essay are adapted to fit rational narrative that I have in my brain.

This is the beginning of the essay.

The four phases are categorized into the following
1. transaction an physical assets
2. transaction of electron
3. transaction of information
4. transaction of digital assets

Each phase increase efficiency of transactions which depends on three factors: object, process, and rules.

Focusing on economic perspective, one can think of an objects as entities with ownership and process as a automatic process of manipulating of objects. Example of processes are movement, composability, and duplication etc. Lastly, rules are constraints imposed upon computation of processes and objects.

Using analogy of physic, rules are physic law such as gravity. Gravity put constraint on movement (process) of objects.

Rules are given. No one can change the rules. However, given a set of rules, object and process can be manipulated.

This is a new idea that I have as of [2022-04-15 Fri], so notation may be imprecise, but I will try my best to explain.

$object = process_1(objects, process_2(...))$

I derived an equation of object as followed

where An object is a output of process. A process can take N number of process and M number of objects as parameters.

Each step of assets transaction evolution create new types of object and new type of process. Total value of wealth are expanded from creation and utilization of new objects and new processes. During the first phase, assets are physical assets such as tree and rock. Discovers and inventions of fire, weapon, road, car allows new creation of processes like toasting a bread, chopping tree, and riding a car. In the second phase, "transaction of electron" create new objects like electric, light bulb, and xray and new processes involving the objects. With the invention of computer, the next phase "transaction of information" begins. It allows movement of bits and bytes which represent information. This further increases efficiency of communication and exchange of information. However, information alone is not enough to compose and exchange digital assets. The missing puzzle is ownership. And the technology that allows for the digital assets to be exchanged is blockchain technology. New form of objects includes NFT and crypto. One may argue that digital assets already exists during "transaction of information" phase. That's correct. To be clear, blockchain technology doesn't create digital assets. Blockchain technology expands creation of new digital asset and enable digital assets to be transacted. Hence, the name of the blog.

This blog provide one mental framework to think about the world and emphasize on significant of blockchain technology.

That's it.
Peace..

** TODO Asset vs Property vs Security
:PROPERTIES:
:ID:       b3436ffd-1c76-486c-9a31-7b33d3018313
:END:

Property is things that can be owned. By definition, property exclude governance aspect. Properties of a property is open, permissionless, and unsensorable.

Property are better stored fo value than money because it has utility, but they are not a good medium of exchange.

Asset is things that hold value. In this case, value is evaluated based on suppply-demand mechanism.

Security is a financial instrument. It is a type of financial asset. Government of a country determines asset that can be categorized as security or non-security.

** Incentives Of Owning Money. :money:philosophy:
:PROPERTIES:
:EXPORT_FILE_NAME: Incentives Of Owning Money.
:ID:       e8682929-2a0a-4147-9769-62784a3ef245
:END:
- Edit History
  - last edit on [2022-07-30 Sat]

Money is the most flexible medium of exchange. For more detail please refer to my blog named "Money Is A Type of Token."

Motivation drive efforts. Effort is a seed of creation and innovation. It just happens that money provides universal motivation due to its utility which is measured by speed of conversion from itself to other assets. Money has fastest conversion rates. It is important to remember that Utility of token or money exists at all as a result of shared believe.

That's it.
Peace.

** Money Is A Type Of Token. :tokenomic:money:philosophy:
:PROPERTIES:
:ID:       d38a900f-636c-4e40-ac2c-37c0a979115d
:EXPORT_FILE_NAME: Money Is A Type Of Token.
:END:
- Edit History
  - last edit on [2022-07-30 Sat]
    - I can refine this blog more by consolidating the current content to my notes on roam research. I don't have time to do this at the time of writing.

In theory, there is no need for "medium" of exchange. Any exchange can be anything as long as seller and buyer agree upon. Therefore, one can argue that there will always exist a sequence of exchanges of agreements that satisfy any pair of sellers and buyers. In theory, this approach of exchange is possible only because there exists a hidden assumption that everyone knows each other and an exchange is completed in an instant without time delay. In practice, an exchange is contraint by time and spatial distant in physical world. That's it. using this approach, not all exchanges are possible and exchanges that are possible are not efficient.

In the other word, properties of exchangeable agreement are
1. Resistance to falsification

But, what exactly make exchangeable items efficient for adoption in an economy?

Imagine a graph of items where nodes are items and edges are agreeable exchange, we get a clique. The most efficient medium of exchange is a node with highest betweeness centrality. Clique has the least betweeness centrality and star graph has the highest betweeness centrality.

But what item should be picked as a medium of exchange? Its properties are as followed [fn:1]

1. Transportable
2. Common and obtainable
3. Low preservation cost
4. Recognizable
5. Consistent
6. Dividable
7. Large market value with respect to weight and volume
8. Value common holdings
9. The only utility of medium of exchange is its ability to be medium of exchange and nothing else.

Ultimately, properties of medium of exchange are required to guarantee absolute trust between sellers and buyers that an exchange happened according to their agreements. To put it simply, medium of exchange must be undoubtedly trusted by the two parties. That's it. Any medium of exchange is a share believe of trust that the medium satisfies its properties.

Money is a share believe in modern economic. One can think of money as global shared believe. In tokenomics, token are a share believe within community. One can think of token as local shared believe. Similar to economic in general, value of token depends on supply and demands. Lets value of meme factor be between 0 to 1. Due to the locality property of token, memes factor is also required to evaluate level of community shared believe. Note that meme factor of money is 1.

#+BEGIN_QUOTE
The only utility of medium of exchange is its ability to be medium of exchange and nothing else.
#+END_QUOTE

This property of medium of exchange is subtle but really important. This is because, without this property, it is possible for the exact copied of the same medium of exchange to be valued unevenly within the economy.

That's it.
peace.

*** Footnotes
[fn:1] https://corporatefinanceinstitute.com/resources/knowledge/economics/medium-of-exchange/

* Data
:PROPERTIES:
:ID:       84ff272e-0938-49be-bf52-e1020c0d00cd
:END:
#+BEGIN_SRC python :results output :cache yes
import requests
import json
import prettytable
from pathlib import Path
import pandas as pd
import numpy as np
headers = {'Content-type': 'application/json'}
data = json.dumps({"seriesid": ['LNS11300000'],"startyear":"2019", "endyear":"2022"})
p = requests.post('https://api.bls.gov/publicAPI/v1/timeseries/data/', data=data, headers=headers)
json_data = json.loads(p.text)
data_dir = Path("/home/awannaphasch2016/Data/Economics/us_bureau_of_labor_statistics/")
data = []
for series in json_data['Results']['series']:

    # x =prettytable.PrettyTable(["series id","year","period","value","footnotes"])
    seriesId = series['seriesID']
    for item in series['data']:
        year = item['year']
        period = item['period']
        value = item['value']
        footnotes=""
        # for footnote in item['footnotes']:
        #     if footnote:
        #         footnotes = footnotes + footnote['text'] + ','
        if 'M01' <= period <= 'M12':
            # x.add_row([seriesId,year,period,value,footnotes[0:-1]])
            data.append([seriesId,year,period,value))
    data_df = pd.DataFrame(data, columns=["series id","year","period","value"])
    data_df.to_csv(str(data_dir / (seriesId + '.txt')),'w')
    print(data_df.head)
    # output = open(str(data_dir / (seriesId + '.txt')),'w')
    # output.write (x.get_string())
    # output.write (x.get_string())
    # output.close()
print('done')
#+END_SRC

#+RESULTS[c5548b39e963b42d1691503d01101f6a9e6cafbd]:
