#+TITLE: Note Taking Note
#+hugo_base_dir: /home/awannaphasch2016/org/projects/sideprojects/website/my-website/hugo/quickstart
#+filetags: note_taking

* blog :blog:
** Philosophy and Meta Physics of "Notes Taking" :note_taking:philosophy:
:PROPERTIES:
:EXPORT_FILE_NAME: Philosophy and Meta Physics of "Notes Taking"
:END:
Note taking is a skill that everyone seems to think that they have "solved" it. Whatever that means. They are not interested in investing their time to improve their note taking skill.

No interest. No skill. No framework.

Regardless of my critique, I think they draw conclusion fairly. Why? around 6 out of 10 people are knowledge worker [fn:1]. A subset of those need to use note at all. A subset of those who use notes need to create reusable notes. A subset of those who create reusable note needs the notes to be reusable forever.

Even professors, the highest regard of knowledge workers, most of them don't have reusable notes beyond paper they publish. I would argue that published paper is NOT a good note. I explain this point in my blog titled "Writing a 'Blog'." In short, I categorized published paper as "blog that you write for others to read." Good reusable notes should be "blog that you write for yourself."

To put it simply,
#+BEGIN_QUOTE
People Don't Know How To Create Or Use Notes At The Highest Efficiency.
#+END_QUOTE

I was the same as them, but I came to an inevitable conclusion that my memory sucks. I tried to train for it. No help. It is the first time I reached my genetic limit.

Memory is a bitch. Sometimes, it make you believe that you/someone did something but you/someone didn't do it.

Imagine this scenario. you read the whole book on something. Did all the exercise. Make sure that you "understand" it. For an interval of time after you learned it, You remember it. You can explain it. You can use it. But then, you didn't have to use this knowledge for 3 years. You still believed that you understand it. You was an expert on it once. But reality hits... Now you don't remember jack shit.

This is the point where people start telling me "it is because you didn't 'understand' it." My usual respond is "how do you evaluate that you understand something?" Every answer that I ever get I did and I passed the evaluation process they suggested. They suggestions don't work for me, so like always I created my own. On this topic, I wrote an article titled "Assess Your Level of Understanding."

If you at some point think, you can solve memory issue with "space repetition." No, it is not. It helps you understand facts, but doesn't help you evaluate your level of understanding.

After acknowledging my genetic limitation, I start writing notes with a hope that I will just read my notes when I don't remember something. Another problem arises. Sometimes, I can't find it. Sometimes, it takes too long to find. It's just not efficient. I realized that using note to help with memory retrieval is an engineering problem rather than a fundamental flaw in the approach.

After 3 years of experimentation, I think I solve it.

When I talk about note taking to people, I usually asked "How do you take note?," "When do you use your notes?" etc. What I was trying to get at is the following:
#+BEGIN_QUOTE
What is the property of your notes?
and
what is the constraint in which you interact with your notes?
#+END_QUOTE

The two questions is a sub question that ask "What problem do you expect your note to solve?" I don't know about others.

Before answering the two questions let me define notes as followed.
#+BEGIN_QUOTE
Note is a collection of text and picture.
#+END_QUOTE

That's it. It's is my brain. I built my own vocabulary for my own use.

My answer to the following question is as followed.
I want my notes to have the following properties:
1. notes should be quickly extracted and stored from anywhere.
2. notes should be able to grow organically.
3. notes should be easily retrievable at the speed of thought.

The first properties are idea of "second brain." The second property is an idea of "Zettlekasten." The third property is there to guarantee maximum efficiency.

I have three types of notes.
1. a note as a question.
2. a note as an answer.
3. a note as a collection of question.

The first two type falls into "a note as a seed" followed a terminology introduced by "Zettlekasten." The third type is there to help maximize speed of note retrieval. This derived from a premise that people think in form of "questions", but people communicate to ourselves or to other in form of concepts which are represented by either words or pictures. I argue that "a concept is a collection of questions" [fn:2]. More abstractly, I argue that thought is a "field space," a question is a "vector," and a concept is a "point" pointed to by a vector.

Lastly, I want to mention about "second brain" approach. At this point, second brain is a field with theories. It explains what it is, but doesn't say anything about frameworks to build second brain. I write note taking framework in my blog titled "Note Taking Pipeline Framework."

That's it.
Peace.

*** Footnotes
[fn:1] [[https://www.altmansolon.com/insights/staying-at-home-why-20-million-workers-will-continue-remote-work-after-covid-19/#:~:text=There%20are%20approximately%20100%20million,60%25%20of%20the%20labor%20force][Staying at home: Why 20 million worker will continue remote work after COVID-19]].
[fn:2] [[https://roamresearch.com/#/app/AdaptiveGraphStucture/page/O1Ne7sMZp][a concept is a collection of questions]]

** Note Taking Pipeline Framework. :note_taking:
:PROPERTIES:
:ID:       14e34658-9070-4b59-a39f-fb1a4054fba8
:EXPORT_FILE_NAME: Note Taking Pipeline Framework.
:END:

I propose "Note Taking Pipeline Framework" as my take on how I implement my "second brain." I would argue with a high degree of certainty that this framework is the best in the world without degree of exaggeration.

I think of note taking as a type of data storage with a property that satisfy my note taking philosophy. I wrote about philosophy of note taking in my blog titled "Philosophy and Meta Physics of 'Notes Taking'".

My pipeline has 3 components: note lake, note warehouse, and note compression. I will not go into implementation of each components because its every changing, but the framework always stands.

First, characteristics of note lake is as followed:
#+BEGIN_QUOTE
note is easily imported from external source without requirement on structure of data.
#+END_QUOTE

Secondly, Characteristics of note warehouse is as followed:
#+name: characteristic_of_note_warehouse
#+BEGIN_QUOTE
1. all notes are structured based on relevancy.
2. all notes are queryable via a question-oriented search.
#+END_QUOTE

I derive characteristics of note warehouse from my note taking philosophy, see my blog titled "Philosophy and Meta Physics of 'Notes Taking'," where the first point is solved by one of my note types called "a note as a collection of question." Furthermore, on the second point, it is important to note that there is no requirement that all quried data must share any degree of relevancy, instead, the only constraint is that all related note that satisfied question-oriented query must be returned.

Lastly, characteristics of note compression are as followed:
#+BEGIN_QUOTE
content of note is expressive via one or more forms of =representation of your understanding=.
#+END_QUOTE

I wrote about =representation of understanding= in my blog titled "Access Your Level of Understanding."

I haven't covered how to use this note taking pipeline. I will cover it in other blog.

That's it.
Peace.
