#+TITLE: Philosophy Note
#+hugo_base_dir: /home/awannaphasch2016/org/projects/sideprojects/website/my-website/hugo/quickstart
#+filetags: philosophy


* Blog :blog:
:PROPERTIES:
:ID:       2d79e42c-518a-42ba-881e-513d3e245ef7
:END:
** TODO Philosophy of decision making of an open source project as public goods.
:PROPERTIES:
:ID:       c8fe0a23-ab74-4492-b698-b3b1eab272f2
:END:

Open source opens to public information of programmable objects for reusability. This doesn't necessary required decision pipeline to be decentralized. [fn:2]

The core of design of any open source project must decide on trade-off between degree of specialization (such as seamless integration; Apple is an example of this.) or generalization (aka modularity; Linux is an example of this) [fn:2]. In my opinion, I believe that trade off between generalization and specialization are emphasized at different degree. This depends on layer of programmable solution stacks, open source projects provide. This derives from the following hypothesis: "There exists no solution for project with maximum generalizibility that can solve a problem with any degree of specialization."

[incentive misalignment between capitalism and freedom of exchange of ideas]
[tragedy of common]
[problem of incentive misalignemnt of semantic versioning between developing better technology and users]

** Assess Your Level of Understanding :story_telling:
:PROPERTIES:
:ID:       f1d0f95b-b3ce-4136-8103-2ecbe85c1f97
:EXPORT_FILE_NAME: Assess Your Level of Understanding
:END:

Ask youself the following question.
- How do you know your understand something?
- How can you access much do you understand it?
- If you don't fully understand it yet, is there a way you can make a snapshot of things that you don't understand such that you can replace this snapshot whenever a better "version" available to you.

Why ability to assess your level of understanding it important? you asked.

This allows for smaller "smallest unit of X" [[cite:&wanna2022smallest]] where X = understand from whether you understand it or not (yes/no) to how much do you understand it (level of confident) with high level of precision and a accurate representation of your bias and believe [[cite:&wanna2022smallest]].

There are two ways to take a "snapshot" of your understanding either with pictures or narratives. There are trade off between the two types. Most of the time both types of snapshot should be taken.

Taking snapshot with pictures has an advantage that one recalls the snapshot quickly when one sees the picture. Disadvantage is that pictures lacks precision. Not all believe can be clearly draw into pictures. That's it. It is a trade off between =speed of memory retrieval= and =precision of the memory=. This approach also helps to quickly create =spin-off demo= of snapshot for thought experiments.

Another approach is narrative. Aswath Damodaran, famously known as "Dean of Valuation", writes a book on this approach called "Narrative and Numbers: The Value of Stories in Business" [[cite:&damodaran2017narrative]]. The theme of the book is a good usage of using narrative to create a snapshot of believe. The book also mentions using number to increase precision of snapshot. Other ways to use narrative is to take a snapshot of "things that you don't yet fully understand." Usually, "things that you don't fully understand" are believe of others. For example, when reading research paper, when a respectable author in a certain area of expertise says somethings as a matter of fact, but you don't really understand why it is true. You still take his word for it. I call this "transfer of credibility".

Linking back to "Narrative and Numbers: The Value of Stories in Business" [[cite:&damodaran2017narrative]], number is indeed the most accurate representation of reality. However, guiding narrative purely using numbers require extensive research efforts. Time is limited. Although guiding narrative with number is the highest quality of narrative, no one always have time for that.

What are other form of believe representation that one can use to create a narrative? Ranking from lowest to highest quality.
1. narrative via examples.
2. narrative via transfer of credit
3. narrative via logic.

The use of numbers falls into is =narrative via logic=.

Since this article is written for me, this "hierarchy" of believe representation is "obvious" to me enough, so I will omit explaining it.

That's it.
Peace.

*** Bibliography :ignore:
:PROPERTIES:
:ID:       20e6d0d9-b138-4804-a25b-f1c7deb56b55
:END:
bibliography:/home/awannaphasch2016/org/papers/org-mode-bibtex.bib

** Freedom and Power are two sides of the same coin. :freedom:power:
:PROPERTIES:
:ID:       81a5be55-771e-4700-a97f-a630ff331bd9
:EXPORT_FILE_NAME: Freedom and Power are two sides of the same coin
:END:
According to dictionary, freedom is defined as
#+BEGIN_QUOTE
The power or right to act, speak, or think as one wants without hindrance or restraint.
#+END_QUOTE

Power is defined as
#+BEGIN_QUOTE
The capacity or ability to direct or influence the behavior of others or the course of events.
#+END_QUOTE

That's is power is defined by abilities to restrict others' freedom. Therefore, by definitions, an individual with more power has more freedom than others. Freedom cannot be defined without existence of power.

Lets imagine for a second that no one can have power over the others. In this case, definition of freedom can be defined by itself and one's ability to be free, for example, a deaf person doesn't have freedom to hear and a mute doesn't have freedom to speak, etc.

Lets a society be a function of its members as shown below in equation ref:3781832087
#+name: 3781832087
$$
society = function(member\_of\_society)
$$

Also assuming that optimizing quality of a society at any point in time is an optimization problem. This implies any properties (features) of a society can be quantified numerically. In this equation, freedom and power is a constraint where ref:5962778360.

#+name: 5962778360
$$
freedom + power = 1
$$

That's it. at any given point in time, a society can reach its maximal freedom by diminishing power to 0. Note, in this context, quality of life is directly dependent on quality of society. And optimal quality of society at any point in time may differ. Lastly, I speculate that happiness directly depends on quality of life only upto a certain threshold.

Since, a society is a function of its population, removing oneself from a society to living alone may result in higher or lower quality of life.

That's it.
Peace.

** Society As A Function Of Attention. :society:attention:
:PROPERTIES:
:ID:       8431506c-aff8-4c87-805e-d8d7731a09ed
:EXPORT_FILE_NAME: Society As A Function Of Attention.
:END:

Incentive is an underlying mechanism that drive society at any scale including individual, group of individuals, and human population as a whole.

Incentive is an abstract concept. Physically, incentives are driven by money, refer to my blog titled "Incentives of Owning Money" for more detail. Another important concept is to accept that money is an indirect form of freedom and power, refer to my blog titled "Blog Freedom and Power are two sides of the same coin" for more detail.

According to argument made in "Sapian" by Yuval Noah Harari, due to increasing complexity of evolution of society, an expert individual with specialized skill is valued more than a wise individual who knows little about everything. The evolution of society require presents of companies.

What is a company?

A company should exist if and only if it satisfies customers need. In reality, a company satisfies its customers' needs by providing options of solutions. A solution is materialized in a form of either a physical product and a service. Nothing else.

company creates products.
Marketing and adverting are adopting as a strategy to increase sell. Goal of marketing is to satisfy need while goal of advertising is to promoting products.
Marketing strategy is to increase sell to marketing budget (sell-to-marketing ratio).


Advertising is a subset of marketing.

Startup create solutions that satisfy niche group. Due to the current era of technology and mechanism of capitalism, a startup is incentivized by growth models to expand to its infrastructure unrelated to its core solutions that justify it existent. Expansion of infrastructures are needed to increase user experiences while using the solutions.

spend more time on the solution -> more attention of its users -> monetize its users' attention.

revenue come from selling solution, selling analysis of its users behavior, selling its users data, and selling its users attentions. Today economy is driven by "attention markets" because its the easiest way to generate revenue. Furthermore, "attention market" is a zero sum game which means the more the company gets attention of its potential clients, the less its competitor can get. Also, due to human bias and explosion of information, unless product is marginally better. Even if the product is marginally better, A company can implement lockdown strategy to make its even harder to its user to switch.

user siwtch when new_product is marginally better than the old product and will be overall more productive solution if trade off of migration due to lockdown is positive.

The current state of technology don't incentized sharing technology. This is because keeping its technology secret can be advantages which is only possible because these technology built upon its own infastructure. Sure, the technology can be generalized for other to use, but it takes time and resource of the company with no obvious benefit. (why use its own resource to help its competitor and lower its advantage.)

Illustrate the current state of technology as graph, we get.
customer - company - function

Ideally, the graph should be like the following.
customer - function - company



* Footnotes

[fn:2] [[https://youtu.be/VcuEm53f5GM?list=PLM4u6XbiXf5qXKZixrDpN3ZSwH_8UabPq&t=1363][Cryptonetworks and Cities: Analogies at 22:43 mins]]
[fn:1] [[https://www.youtube.com/watch?v=VcuEm53f5GM&list=PLM4u6XbiXf5qXKZixrDpN3ZSwH_8UabPq&index=25&ab_channel=a16z][Cryptonetworks and Cities: Analogies]]
