#+title: Story Telling Note
#+hugo_base_dir: /home/awannaphasch2016/org/projects/sideprojects/website/my-website/hugo/quickstart

* Blog :blog:
** Assess Your Level of Understanding :story_telling:
:PROPERTIES:
:ID:       f1d0f95b-b3ce-4136-8103-2ecbe85c1f97
:EXPORT_FILE_NAME: Assess Your Level of Understanding
:END:

Ask youself the following question.
- How do you know your understand something?
- How can you access much do you understand it?
- If you don't fully understand it yet, is there a way you can make a snapshot of things that you don't understand such that you can replace this snapshot whenever a better "version" available to you.

Why ability to assess your level of understanding it important? you asked.

This allows for smaller "smallest unit of X" [[cite:&wanna2022smallest]] where X = understand from whether you understand it or not (yes/no) to how much do you understand it (level of confident) with high level of precision and a accurate representation of your bias and believe [[cite:&wanna2022smallest]].

There are two ways to take a "snapshot" of your understanding either with pictures or narratives. There are trade off between the two types. Most of the time both types of snapshot should be taken.

Taking snapshot with pictures has an advantage that one recalls the snapshot quickly when one sees the picture. Disadvantage is that pictures lacks precision. Not all believe can be clearly draw into pictures. That's it. It is a trade off between =speed of memory retrieval= and =precision of the memory=. This approach also helps to quickly create =spin-off demo= of snapshot for thought experiments.

Another approach is narrative. Aswath Damodaran, famously known as "Dean of Valuation", writes a book on this approach called "Narrative and Numbers: The Value of Stories in Business" [[cite:&damodaran2017narrative]]. The theme of the book is a good usage of using narrative to create a snapshot of believe. The book also mentions using number to increase precision of snapshot. Other ways to use narrative is to take a snapshot of "things that you don't yet fully understand." Usually, "things that you don't fully understand" are believe of others. For example, when reading research paper, when a respectable author in a certain area of expertise says somethings as a matter of fact, but you don't really understand why it is true. You still take his word for it. I call this "transfer of credibility".

Linking back to "Narrative and Numbers: The Value of Stories in Business" [[cite:&damodaran2017narrative]], number is indeed the most accurate representation of reality. However, guiding narrative purely using numbers require extensive research efforts. Time is limited. Although guiding narrative with number is the highest quality of narrative, no one always have time for that.

What are other form of believe representation that one can use to create a narrative? Ranking from lowest to highest quality.
1. narrative via examples.
2. narrative via transfer of credit
3. narrative via logic.

The use of numbers falls into is =narrative via logic=.

Since this article is written for me, this "hierarchy" of believe representation is "obvious" to me enough, so I will omit explaining it.

That's it.
Peace.


*** Bibliography :ignore:
bibliography:/home/awannaphasch2016/org/papers/org-mode-bibtex.bib
