#+title: Wiki Note
#+hugo_base_dir: /home/awannaphasch2016/org/projects/sideprojects/website/my-website/hugo/quickstart
#+filetags: wiki

* Blog :blog:
:PROPERTIES:
:ID:       d064d8d7-82ef-442e-8701-2f3bd5c40f82
:END:
** TODO A Note on Federate Wiki :federate_wiki:

** TODO Philosophy, Implementation, Utility Of Ideas Organization.
*** Connectivity of idea as data
**** spatial connection
***** local
****** before www
Zettlekasten (connecting ideas via human language)
Hypercard [fn:2] (connecting idea via "card")
wiki (connecting ideas via hypertext, a sequence of characters.)
***** global
www (connecting applications via ip address exists on the internet).
wikipedia (only 1 version can exists via consensus of the crowd)
***** local-global
all modern "information management tools" e.g. roam research, emacs, notion. Their differences are address in
Detail of implementation is addressed in "computability of ideas as data"

**** spatial-temporal connection
***** next step is we need to create local network of idea that can interact freely online.
****** federated wiki (global and local wiki are connected via commit changes, version control's commit history. spatial-temporal connection)

*** Protocol to connect idea as data.

page, block, backlink (first introduced by roam research), visual connection (drawing, mindmaps)

**** I think a page should have the following: template, data, power of data computability.

**** using metadata
- tags
- timestamp
- source reference
*** Compatibility of idea as data
The differences lie in framework's design of how data is structured, connect spatially, or temporal (see below in "temporal connection section").

On top of organization design, compatibility of data is another important design different. (
1. notion way of storing data directly in database.
2. unix way of data as characters which adopted by emacs
3. federate wiki way of using API to send and receive data.
*** Searchability of idea as data
data query, pattern matching, language embedding (GPT-3), jump between neighbor
*** Utility of ideas as data
**** manually
recall, creativity, taking a snapshot of =representation of understanding=
**** automatically (this is new)
resembrance agent, completion, recommendation
*** Footnotes
:PROPERTIES:
:ID:       bacfd013-689e-4f9c-83a2-da12800729ab
:END:
[fn:2] The computer chronicles - Hypercarrd (1987)
** Wiki Wars :history:
https://www.google.com/search?q=does+wikipedia+win+wiki+wars%3F&rlz=1C1CHBF_enUS941US941&oq=does+wikipedia+win+wiki+wars%3F&aqs=chrome..69i57j33i160l4j33i299.8877j0j7&sourceid=chrome&ie=UTF-8

** What the f*** is wiki.c2.com? and its potential for mainstream adoption.
:PROPERTIES:
:EXPORT_FILE_NAME: What the f*** is wiki.c2.com? and its potential for mainstream adoption.
:ID:       3f813aae-77e5-4186-8dd8-b3af13a3ff75
:END:

- last edit
  - [2022-06-26 Sun]

One of my life long projects is to build an =index protocol= using tokenomics for thought sharing. For now, on [2022-06-26 Sun], I call it "The Forest."

On [2022-06-26 Sun], I stumbled upon =wiki.c2.com=. I was reading about it for a couple hours, and =wiki.c2.com= seems to share lots of philosophy that =The Forest= holds. Two hours in, however, I can't seem to get a grip of some very basic stuff like how to read it? what is it for? Words they use can only be understood by those who already know it. Each page is structured like a blob of discussions. There are no sense of direction. What I mean is. Whenever I attempt to read one of the page, I can't answer "Where do I start reading this?"

I designed The Forest to avoid this type of problem. The Forest is designed such that scope of things to read is narrowed by searching for questions one has before searching for answer.

Studied history of Stack Overflow, I am aware that The Forest attempts to solve the same problem that Stack Overflow solved. Stack Overflow was founded as one of many question-answering platform. However, the differences between Stack Overflow and its competitors are that users can find answer easily on Stack Overflow. It solves this by having superior "answer indexing mechanism." If I am right about comparing The Forest to Stack Overflow, The Forest will be Stack Overflow of "Sharing Ideas as Wiki" platforms where =wiki.c2.com= is an example.

According to comments on a Reddit thread, people regards =wiki.c2.com= as "one gigantic cultural artefact that needs to stay afloat." [fn:1] One of the user nicely summarized =wiki.c2.com= as followed:

#+BEGIN_QUOTE
[Wiki.c2.com is] the first wiki wiki and the model for Wikipedia, the Portland Pattern Repository was a place where many of the principles of Agile software development were hashed out through discussion of the leading members of that movement. It was closer to the discussion pages of Wikipedia, where someone would write on a topic, and another would add more dimension or a counterpoint to what was written. Instead of creating a page of what, say, Extreme Programming was, pages full of discussion of how it was implemented on site or how it could be improved were generated; when it became too large, someone might refactor that page into several different pages, such as XP Principles, XP Practices, XP implementations, and so on.
#+END_QUOTE

Another user jokingly make a responds comment as followed:
#+BEGIN_QUOTE
Elsewhere on the net, there are two sites that convention mandated a warning flag for fear of clicking the rest of the afternoon following interesting things. TVTropes... and =wiki.c2.com=.
#+END_QUOTE

To me, =wiki.c2.com= feels like an open bar for hippie thinkers to engage in any topic on their minds. Its one of those place where anyone can endlessly wander (from page to page) and get lost like a runaway vacation. In a way, it comforts me. I recalled this feeling of comfort. I encountered a place/culture like this before. And it was =emacs=. My first love.

On a serious note, the problem I found related to implementations of Wiki are the followings:
1. Different wiki has different protocol of how to interact with it.
2. Wikis lacks credibility as a "source of truth." They functionality and usage resemble platforms that encourage honest, open, and opinionated discussion.
3. People misuse public wiki as their own back of an envelope's scratch pad.
4. It is not useable beyond a fun "get away" read.

Point 1 and 2 can be fixed with indexing protocol with tokenomics. An example of indexing protocol is [[https://thegraph.com/en/][The Graph]] which is described on their main site, as of [2022-06-26 Sun], as "an indexing protocol for querying networks like Ethereum and IPFS". In summary, The Graph is indexing protocol for data while The Forest is indexing protocol for thought.

On the last point, point 3, I see that it can be fixed by using version control to "fork" idea of others and "grow it yourself" (Grow as in growing =seeds of thought= into your own =evergreen forest=). Forking process of existing wikis already existed [fn:1], but the current practice of forking doesn't fully embrace full functionality of version control. This is the point I wanted to make. It is possible to fully replicate version control functionality. To be exact, replicating Git way of doing version control as it is the rightful winner of =version control war=. This includes "staging," "commit," "stashing," "blame," and "cherry picking." Go crazy. Be creative.

Furthermore, on point 4, to enhance usability and embrace The Forest's ideology, using a combination of =language server protocol= (LSP) of server-client like approach and use =resembrance agents= as an API to provide utilities such as providing list of (thought) completion via =(thought) completion framework=.

Ultimately, integrating and using =The Forest= driven by =resembrance= agent capability should feel no different from =thinking.= That's it. A complete extension of your brain's capacity. My goal standard of what =second brain= should be.

That's it.
Peace.

*** Footnotes

[fn:1] [[https://news.ycombinator.com/item?id=12705774][The c2 wiki was down]]
